"""
Citation Validation
===================

Validates citations produced by the grounded answer generator.

Security principles:

1. Citation must use HTTPS.
2. Citation hostname must be explicitly allowed.
3. Citation must exactly match a URL retrieved from evidence.
4. Citation must not be fabricated by the LLM.
5. Duplicate citations are removed.
6. Malformed URLs are rejected.
7. Grounded refusals may contain zero citations.
8. Supported sources include Stack Exchange and Open-Meteo.
"""

from urllib.parse import urlparse


# ============================================================
# Allowed Citation Domains
# ============================================================

ALLOWED_DOMAINS = {
    # Stack Exchange / Stack Overflow
    "stackoverflow.com",
    "stackexchange.com",

    # Open-Meteo
    "api.open-meteo.com",
    "geocoding-api.open-meteo.com",
}


# ============================================================
# Maximum Citation Count
# ============================================================

MAX_CITATIONS = 10


# ============================================================
# URL Normalization
# ============================================================

def _normalize_url(url: str) -> str:
    """
    Normalize a citation URL without changing its meaning.
    """

    return url.strip().rstrip(".,;)")


# ============================================================
# Domain Validation
# ============================================================

def _is_allowed_domain(hostname: str) -> bool:
    """
    Check whether a hostname belongs to an explicitly allowed
    citation domain.

    Subdomains are supported while lookalike domains are rejected.
    """

    hostname = hostname.lower().rstrip(".")

    if hostname in ALLOWED_DOMAINS:
        return True

    return any(
        hostname.endswith("." + domain)
        for domain in ALLOWED_DOMAINS
    )


# ============================================================
# URL Security Validation
# ============================================================

def _validate_url(
    url: str,
    evidence_urls: set[str],
) -> tuple[bool, str]:

    if not isinstance(url, str):
        return False, "Citation must be text."

    url = _normalize_url(url)

    if not url:
        return False, "Citation URL is empty."

    # --------------------------------------------------------
    # Parse URL
    # --------------------------------------------------------

    try:
        parsed = urlparse(url)

    except ValueError:
        return False, "Citation URL is malformed."

    # --------------------------------------------------------
    # HTTPS requirement
    # --------------------------------------------------------

    if parsed.scheme.lower() != "https":
        return False, "Citation does not use HTTPS."

    # --------------------------------------------------------
    # Hostname
    # --------------------------------------------------------

    hostname = parsed.hostname

    if not hostname:
        return False, "Citation has no valid hostname."

    hostname = hostname.lower().rstrip(".")

    # --------------------------------------------------------
    # Allowed domain
    # --------------------------------------------------------

    if not _is_allowed_domain(hostname):
        return False, "Citation domain is not allowed."

    # --------------------------------------------------------
    # Reject credentials
    # --------------------------------------------------------

    if parsed.username or parsed.password:
        return False, "Citation URL must not contain credentials."

    # --------------------------------------------------------
    # Exact evidence match
    # --------------------------------------------------------

    if url not in evidence_urls:
        return (
            False,
            "Citation was not present in retrieved evidence.",
        )

    return True, ""


# ============================================================
# Main Citation Validator
# ============================================================

def validate_citations(
    answer: str,
    evidence: list[dict],
    citations: list[str] | None = None,
    evidence_sufficient: bool = True,
) -> dict:
    """
    Validate citations generated by the answer generator.

    Parameters
    ----------
    answer:
        Generated answer text.

    evidence:
        Retrieved research evidence.

    citations:
        Explicit citation URLs returned by the answer generator.

    evidence_sufficient:
        Whether the evidence evaluator determined that enough
        evidence exists to answer the question.

        If False, a grounded refusal may legitimately contain
        zero citations.

    Returns
    -------
    dict
        {
            "valid": bool,
            "citations": list[str],
            "reason": str
        }
    """

    # ========================================================
    # Validate answer
    # ========================================================

    if not isinstance(answer, str):

        return {
            "valid": False,
            "citations": [],
            "reason": "Answer is not valid text.",
        }

    if not answer.strip():

        return {
            "valid": False,
            "citations": [],
            "reason": "Answer is empty.",
        }

    # ========================================================
    # Validate evidence
    # ========================================================

    if not isinstance(evidence, list):

        return {
            "valid": False,
            "citations": [],
            "reason": "Evidence is not a valid list.",
        }

    # ========================================================
    # Build evidence URL allow-list
    # ========================================================

    evidence_urls: set[str] = set()

    for item in evidence:

        if not isinstance(item, dict):
            continue

        url = item.get("url")

        if not isinstance(url, str):
            continue

        url = _normalize_url(url)

        if url:
            evidence_urls.add(url)

    # ========================================================
    # Validate citation container
    # ========================================================

    if citations is None:

        return {
            "valid": False,
            "citations": [],
            "reason": (
                "No explicit citations were provided by "
                "the answer generator."
            ),
        }

    if not isinstance(citations, list):

        return {
            "valid": False,
            "citations": [],
            "reason": "Citations must be provided as a list.",
        }

    # ========================================================
    # Citation count limit
    # ========================================================

    if len(citations) > MAX_CITATIONS:

        return {
            "valid": False,
            "citations": [],
            "reason": "Too many citations were provided.",
        }

    # ========================================================
    # Grounded refusal
    # ========================================================

    """
    If the evidence evaluator says there is insufficient evidence,
    zero citations is valid.

    Example:

        Answer:
        "I don't have enough grounded evidence..."

        Citations:
        []

    This is not a citation failure because the agent is explicitly
    declining to make an unsupported claim.
    """

    if not evidence_sufficient and len(citations) == 0:

        return {
            "valid": True,
            "citations": [],
            "reason": (
                "Grounded refusal contains no citations because "
                "the available evidence was insufficient."
            ),
        }

    # ========================================================
    # Validate every supplied citation
    # ========================================================

    validated_citations: list[str] = []

    for citation in citations:

        if not isinstance(citation, str):

            return {
                "valid": False,
                "citations": validated_citations,
                "reason": "Citation must be text.",
            }

        normalized = _normalize_url(citation)

        valid, reason = _validate_url(
            normalized,
            evidence_urls,
        )

        if not valid:

            return {
                "valid": False,
                "citations": validated_citations,
                "reason": reason,
            }

        # ----------------------------------------------------
        # Remove duplicates
        # ----------------------------------------------------

        if normalized not in validated_citations:

            validated_citations.append(normalized)

    # ========================================================
    # Grounded answer requires at least one citation
    # ========================================================

    if evidence_sufficient and not validated_citations:

        return {
            "valid": False,
            "citations": [],
            "reason": (
                "Grounded answer contains no validated citations."
            ),
        }

    # ========================================================
    # Success
    # ========================================================

    return {
        "valid": True,
        "citations": validated_citations,
        "reason": (
            "All citations are HTTPS URLs from allowed domains "
            "and exactly match retrieved evidence."
        ),
    }
